from enum import Enum


class FN(Enum):
    FN1 = "Function 1: Industry General Information"
    FN2 = "Function 2: Multiples Table Explanation"
    FN3 = "Function 3: Risk Table Explanation"
    FN4 = "Function 4: Barriers To Entry Checklist Explanation"
    FN5 = "Function 5: Main Activity Explanation"
    FN6 = "Function 6: Products and Services Explanation"
    FN7 = "Function 7: Major Players Explanation"
    FN8 = "Function 8: Definition and Summary"
    FN9 = "Function 9: Revenue Figure Card Explanation"
    FN10 = "Function 10: Profit Figure Card Explanation"
    FN11 = "Function 11: Profit Margin Figure Card Explanation"
    FN12 = "Function 12: Enterprises Figure Card Explanation"
    FN13 = "Function 13: population by race ethnicity card Figure Card Explanation"
    FN14 = "Function 14: population by marital status card Figure Card Explanation"
    FN15 = "Function 15: population by relationship and household card Figure Card Explanation"
    FN16 = "Function 16: population by gender card Figure Card Explanation"
    FN17 = "Function 17: population by educational attainment status card Figure Card Explanation"
    FN18 = "Function 18: demographic overview card Figure Card Explanation"
    FN19 = "Function 19: HouseHold by size Figure Card Explanation"
    FN20 = "Function 20: civilian population Figure Card Explanation"
    FN21 = "Function 21: HouseHolde Income Figure Card Explanation"
    FN22 = "Function 22: General Figure Card Explanation"
    FN23 = "Function 23: state of supply and demand Figure Card Explanation"
    FN24 = "Function 24: market size Figure Card Explanation"
    FN25 = "Function 25: market geography Figure Card Explanation"
    FN26 = "Function 26: Target Customer Figure Card Explanation"
    # FN27 = "Function 19: pop card Figure Card Explanation"
    # FN28 = "Function 19: pop card Figure Card Explanation"
    # FN29 = "Function 19: pop card Figure Card Explanation"
    # FN30 = "Function 19: pop card Figure Card Explanation"
    # FN31 = "Function 19: pop card Figure Card Explanation"
    # FN32 = "Function 19: pop card Figure Card Explanation"

